00-einführung:
  source: 00-einführung.rst
  css:
    - css/campus02.css
  template: default
  auto-console: false
  skip-help: true
  skip-notes: true
01-restful:
  source: 01-restful.rst
  css:
    - css/campus02.css
  template: default
  auto-console: false
  skip-help: true
  skip-notes: true
02-javascript:
  source: 02-javascript.rst
  css:
    - css/campus02.css
  template: default
  auto-console: false
  skip-help: true
  skip-notes: true
